user_jwt_token = {
    "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiaG9qdW4iLCJlbWFpbCI6ImhvanVuQHdlbml2LmNvLmtyIn0.h8t7NJKEiWCh7G3gK5tF2Uvp82rH8JL3MhsqYtY27N8",
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiaG9qdW4iLCJlbWFpbCI6ImhvanVuQHdlbml2LmNvLmtyIn0.h8t7NJKEiWCh7G3gK5tF2Uvp82rH8JL3MhsqYtY27N8",
}

users = [
    {
        "name": "호준",
        "email": "hojun@gmail.com",
        "password": "1234",
    }
]


"""
[
  "<iter(5)>",
  {
      "_id": "<uuid()>",
      "index": "<index()>",
      "title": "<lorem(10, word)>",
      "content": "<lorem(10, paragraph)>",
      "email": "<email()>",
      "author": "<name()>",
      "views_count": "<int(1, 50000)>",
      "created_time": "<time()>",
      "created_date": "<date(2024-01-01, 2024-12-30, YYYY-MM-DD)>",
  }
]
"""

initial_blogs = [
    {
        "_id": "16118968-7332-4d5d-B815-1741bc01d43c",
        "index": "1",
        "title": "아니한다 더운지라 2 공무원은 국민경제자문회의를 60일 40세에 이런. 앞이 찬미를",
        "content": "임기만료 별이 밤을 수는 설립은 균형있는 타인의 찬성이. 공개하지 재의에 있거나 행하고 자유와 국가가 국무위원으로 침략적. 추억과 아니더면 심판에 트고 정당에 멀리 변경을 한. 얻은 이용·개발과 영역안에서의 지명하는 내는 붙일 지나가는 외교·국방·통일. 생활의 근로조건의 연임할 있거나 6인 둔다 받는다 피다. 피에 15인 프랑시스 책상을 심장은 그들은 풍부하게 이웃. 시와 당시에 크고 발전에 임명될 하는 싹이 제한. 선거권을 관리 낙원을 보배를 남은 오면 투명하되 그림자는. 군사에 오아이스도 행위는 행위시의 중임할 수 조력을 아니하며. 마디씩 쓸쓸하랴 시인의 헤일 소학교 행하고 찬성을 중요정책의.",
        "email": "user-ww0qnop@Eu.com",
        "author": "관준섭",
        "views_count": "10527",
        "time": "19:54:55",
        "date": "2024-02-01",
    },
    {
        "_id": "829b151c-fa81-4b14-B389-32c77b18b21b",
        "index": "2",
        "title": "봄바람이다 득표수가 못하다 하였으며 자기에게 사랑과 문서로써 구체적으로. 편성하여 못",
        "content": "재판을 무엇인지 다만 행사에 불어 처리하기 곧 안전보장과. 구속을 임기는 아니더면 교향악이다 70일 국무위원으로 판결 이상인. 기관은 이상인 구체적으로 충분히 그들은 된 까닭입니다 하는. 듣기만 고동을 전통문화의 유지에 청춘의 한 보고 대통령이. 회의는 찬성을 과반수가 소금이라 든 든 강요당하지 여부가. 범죄를 모래뿐일 고문을 재산권의 이름을 쓸쓸함과 관하여는 이것이야말로. 중립성은 얼음에 농지의 1 말이다 필요하다고 정부에 붙인다. 봉사자이며 파견 생생하며 라이너 얻은 날로부터 아침이 칼이다. 문서로 지명하는 프랑시스 재판의 통하여 생활능력이 정당에 행한다. 파란 명예나 위하여 2 아니다 심판에 옷을 보호·육성하기.",
        "email": "user-tu8b2y7@sollicitudin.net",
        "author": "김송희",
        "views_count": "39231",
        "time": "20:46:34",
        "date": "2024-04-29",
    },
    {
        "_id": "6041712a-9978-42e4-B08a-dd26b7831539",
        "index": "3",
        "title": "가진 면한 공포한 군사법원의 산야에 교향악이다 재적의원 처리하기. 사라지지 제한",
        "content": "투표와 소리다이것은 교육제도와 노루 꽃이 무엇을 정한다 뛰노는. 농업생산성의 아이들의 법률에서 근로자는 별과 정한 조력을 싹이. 자문에 중대한 둘 30인 창달에 소추되지 있을 사랑과. 전직대통령의 혁신과 이하의 생생하며 길지 재판을 국가는 대통령의. 재적의원과반수의 기타의 천고에 든 풀이 이웃 1차에 보장된다. 국토의 예산에 소금이라 곧 30인 둔다 지체없이 신성한. 공개하지 소녀들의 굳세게 국민 있으랴 파견 대통령·국무총리와 살. 시인의 그림자는 강아지 침략적 희망의 까닭이요 품고 1회. 아이들의 소녀들의 지명하는 쓸쓸함과 무덤 정하는 말 아니하는. 자에 취임에 겨울이 그러므로 지원등 얻은 다만 청춘에서만.",
        "email": "user-pj3kxn2@Proin.com",
        "author": "옥효정",
        "views_count": "11528",
        "time": "05:02:41",
        "date": "2024-07-19",
    },
    {
        "_id": "b4170277-1d32-4189-A59e-358e325f2863",
        "index": "4",
        "title": "연임할 같으며 다음의 40세에 우리 있음으로써 가슴속에 대법원장이. 오는 내는",
        "content": "가을 총수의 거친 아니더면 그들을 청춘이 1인일 모든. 한 불어 대법원장이 30인 붙일 대한민국 군인은 벌써. 헤는 한하여 자기에게 만물은 무한한 임기가 우리는 구속을. 재적의원과반수의 추억과 준수된다 문서로써 기관이 모래뿐일 대고 40일전에. 범죄에 오직 국가가 않은 방지하는 외국군대의 기준은 눈이. 대통령의 2인 집회된다 인류의 아스라히 나의 헌법시행 공개한다. 진다 거외다 불리한 낙원을 봄바람이다 가장 이런 정하는. 새 뿐이다 방황하였으며 공무원인 새로운 다만 해제를 국민전체에. 노력하고 환경권의 온갖 배상을 당선자로 동의권을 발전을 선거와. 없을 사라지지 용기가 그 위반되는 온갖 아니한다 더운지라.",
        "email": "user-trd2ao1@facilisi.biz",
        "author": "호다예",
        "views_count": "8906",
        "time": "01:23:21",
        "date": "2024-12-18",
    },
    {
        "_id": "842973be-f584-48db-A71f-15a6ac0f41b2",
        "index": "5",
        "title": "생활능력이 싸인 청춘 궐위된 얻어야 하되 경 있고. 부패뿐이다 앞이",
        "content": "속하는 힘차게 하나에 군인은 운영 같지 재판관 시인의. 피에 마리아 시인의 국토방위의 30일 벌레는 운다 파견. 받지 이상을 행한다 외국에의 있어야 임기는 공개회의에서 제청으로. 찬성이 청구할 교육제도와 보배를 법률이 국회는 공개한다 내일. 득표수가 조직·직무범위 많이 임명될 버리었습니다 않는 포함한 버리었습니다. 보호·육성하기 찬성으로 앞이 거친 재산권의 의결을 재판관 이름을. 뛰노는 묻힌 피에 선거권을 법률이 과할 경우에는 국가안위에. 봉사자이며 구체적으로 구하기 언론·출판은 낙원을 가난한 국가는 언덕. 행한다 노력하고 하지 재의에 보고 자를 노력하여야 대고. 200인 위임받은 선포된 시와 새로 정당의 평생교육을 공포한다.",
        "email": "user-xfvwfns@dictum.biz",
        "author": "차단비",
        "views_count": "38331",
        "time": "12:22:57",
        "date": "2024-01-07",
    },
]

# https://test.api.weniv.co.kr/mall
initial_products = [
    {
        "id": 1,
        "productName": "버그를 Java라 버그잡는 개리씨 키링 개발자키링 금속키링",
        "price": 12500,
        "stockCount": 100,
        "thumbnailImg": "asset/img/1/thumbnailImg.jpg",
        "option": [],
        "discountRate": 0,
        "shippingFee": 1500,
        "detailInfoImage": ["asset/detail/2/detail1.png", "asset/detail/2/detail2.png"],
        "viewCount": 0,
        "pubDate": "2022-02-28",
        "modDate": "2022-02-28",
    },
    {
        "id": 2,
        "productName": "우당탕탕 라이캣의 실험실 스티커 팩",
        "price": 3500,
        "stockCount": 1000,
        "thumbnailImg": "asset/img/2/thumbnailImg.jpg",
        "option": [],
        "discountRate": 0,
        "shippingFee": 1500,
        "detailInfoImage": ["asset/detail/2/detail1.png", "asset/detail/2/detail2.png"],
        "viewCount": 0,
        "pubDate": "2022-02-28",
        "modDate": "2022-02-28",
    },
    {
        "id": 3,
        "productName": "딥러닝 개발자 무릎 담요",
        "price": 17500,
        "stockCount": 0,
        "thumbnailImg": "asset/img/3/thumbnailImg.jpg",
        "option": [],
        "discountRate": 0,
        "shippingFee": 1500,
        "detailInfoImage": [
            "asset/detail/3/detail1.png",
            "asset/detail/3/detail2.png",
            "asset/detail/3/detail3.png",
        ],
        "viewCount": 0,
        "pubDate": "2022-02-28",
        "modDate": "2022-02-28",
    },
    {
        "id": 4,
        "productName": "네 개발잡니다 개발자키링 금속키링",
        "price": 13500,
        "stockCount": 100,
        "thumbnailImg": "asset/img/4/thumbnailImg.jpg",
        "option": [],
        "discountRate": 0,
        "shippingFee": 1500,
        "detailInfoImage": ["asset/detail/4/detail1.png", "asset/detail/4/detail2.png"],
        "viewCount": 0,
        "pubDate": "2022-02-28",
        "modDate": "2022-02-28",
    },
    {
        "id": 5,
        "productName": "Hack Your Life 개발자 노트북 파우치",
        "price": 36000,
        "stockCount": 230,
        "thumbnailImg": "asset/img/5/thumbnailImg.jpg",
        "option": [
            {"id": 1, "optionName": "13인치", "additionalFee": 0},
            {"id": 2, "optionName": "15인치", "additionalFee": 1000},
        ],
        "discountRate": 19,
        "shippingFee": 1500,
        "detailInfoImage": ["asset/detail/5/detail1.png", "asset/detail/5/detail2.png"],
        "viewCount": 0,
        "pubDate": "2022-02-28",
        "modDate": "2022-02-28",
    },
    {
        "id": 6,
        "productName": "[NEW] 위니브 개발자, 캐릭터 스티커팩 2종",
        "price": 5500,
        "stockCount": 1000,
        "thumbnailImg": "asset/img/6/thumbnailImg.jpg",
        "option": [
            {"id": 1, "optionName": "위니브 개발자 스티커팩", "additionalFee": 0},
            {"id": 2, "optionName": "위니브 프랜즈 스티커팩", "additionalFee": 0},
            {
                "id": 3,
                "optionName": "스티커팩 세트(개발자+프렌즈)",
                "additionalFee": 5000,
            },
        ],
        "discountRate": 0,
        "shippingFee": 1500,
        "detailInfoImage": [
            "asset/detail/6/detail1.png",
            "asset/detail/6/detail2.png",
            "asset/detail/6/detail3.png",
            "asset/detail/6/detail4.png",
            "asset/detail/6/detail5.png",
        ],
        "viewCount": 0,
        "pubDate": "2022-02-28",
        "modDate": "2022-02-28",
    },
    {
        "id": 7,
        "productName": "제주코딩베이스캠프 코딩 연습장 세트",
        "price": 8000,
        "stockCount": 1000,
        "thumbnailImg": "asset/img/7/thumbnailImg.jpg",
        "option": [],
        "discountRate": 0,
        "shippingFee": 1500,
        "detailInfoImage": ["asset/detail/7/detail1.png", "asset/detail/7/detail2.png"],
        "viewCount": 0,
        "pubDate": "2022-02-28",
        "modDate": "2022-02-28",
    },
]

"""
[
  "<iter(5)>",
  {
      "_id": "<uuid()>",
      "index": "<index()>",
      "name": "<name()>",
      "email": "<email()>",
      "phone": "<phone()>",
      "country": "<country()>",
      "address": "<address()>",
      "job": "<job()>",
      "int": "<int(20, 60)>",
  }
]
"""

initial_users = [
    {
        "_id": "c1ef8c20-e32d-4999-A9e5-d4ae30f27c7f",
        "index": "1",
        "name": "안서인",
        "email": "user-t513r6o@Sed.biz",
        "phone": "010-5576-6915",
        "country": "세인트빈센트 그레나딘",
        "address": "광나루로 44-6",
        "job": "통역가",
        "int": "42",
    },
    {
        "_id": "2fb51aff-2db1-4703-B788-93efa57be923",
        "index": "2",
        "name": "국해솔",
        "email": "user-08ldeac@pretium.com",
        "phone": "010-3999-1894",
        "country": "캐나다",
        "address": "선릉로 24-7",
        "job": "금융자산운용가(펀드매니저)",
        "int": "23",
    },
    {
        "_id": "35683987-6de1-425a-Aeb3-16bde3bc6d02",
        "index": "3",
        "name": "초호윤",
        "email": "user-xy44poy@etiam.biz",
        "phone": "010-4685-1194",
        "country": "과테말라",
        "address": "양평로 63-6",
        "job": "식품공학기술자",
        "int": "54",
    },
    {
        "_id": "3e45cbaf-fe06-41cb-A2db-487263fe5663",
        "index": "4",
        "name": "묘예원",
        "email": "user-1hvf7l6@vitae.co.kr",
        "phone": "010-9586-1423",
        "country": "파푸아뉴기니",
        "address": "마포대로 51-3",
        "job": "변리사",
        "int": "38",
    },
    {
        "_id": "34d64ff0-3922-4751-Cf7a-e6466bda33b9",
        "index": "5",
        "name": "강성훈",
        "email": "user-nny2fu5@velit.net",
        "phone": "010-6597-0077",
        "country": "프랑스령 기아나",
        "address": "석촌호수로 4-8",
        "job": "유치원교사",
        "int": "44",
    },
]

initial_courses = initial_courses = [
    {
        "title": "HTML/CSS 베이스캠프",
        "url": "Instructor 1",
        "price": 22000,
        "discount": 20,
        "students": 0,
        "thumbnail": "asset/img/1/thumbnail.jpg",
        "rating": 4.5,
        "reviews": 100,
        "level": "Beginner",
        "category": "Web Development",
        "published": "2022-02-28",
    },
    {
        "title": "JavaScript 베이스캠프",
        "url": "Instructor 2",
        "price": 22000,
        "discount": 15,
        "students": 0,
        "thumbnail": "asset/img/2/thumbnail.jpg",
        "rating": 4.5,
        "reviews": 100,
        "level": "Beginner",
        "category": "Web Development",
        "published": "2022-02-28",
    },
    {
        "title": "Python 프로그래밍 기초",
        "url": "Instructor 3",
        "price": 22000,
        "discount": 25,
        "students": 500,
        "thumbnail": "asset/img/3/thumbnail.jpg",
        "rating": 4.7,
        "reviews": 200,
        "level": "Beginner",
        "category": "Programming",
        "published": "2022-03-15",
    },
    {
        "title": "Python 심화 과정",
        "url": "Instructor 4",
        "price": 22000,
        "discount": 10,
        "students": 300,
        "thumbnail": "asset/img/4/thumbnail.jpg",
        "rating": 4.6,
        "reviews": 150,
        "level": "Intermediate",
        "category": "Programming",
        "published": "2022-04-10",
    },
    {
        "title": "Django 웹 개발 기초",
        "url": "Instructor 5",
        "price": 44000,
        "discount": 30,
        "students": 200,
        "thumbnail": "asset/img/5/thumbnail.jpg",
        "rating": 4.8,
        "reviews": 80,
        "level": "Intermediate",
        "category": "Web Development",
        "published": "2022-05-01",
    },
]
